### ISSUE TITLE
print.rpart digits

### ISSUE THREAD

**Issue by TylerGrantSmith** [bethatkinson/rpart#2]
I'm not positive this is entirely an `rpart` issue.  The print function defined in `rpart.class.R` by default calls `format` using the `digits` global option for the `digits` and `nsmall` parameters.  However, `nsmall` must be between 1 and 20, thus causing the following reproducible error:

```
library(rpart)

fit <- rpart(Kyphosis ~ Age + Number + Start, data = kyphosis)
options(digits = 22)
print(fit)
```
```
Error in prettyNum(.Internal(format(x, trim, digits, nsmall, width, 3L,  : 
  invalid 'nsmall' argument
```

The relevant code from rpart.class.R:
```
print = function(yval, ylevel, digits) {
  temp <- if (is.null(ylevel)) as.character(yval[, 1L])
  else ylevel[yval[, 1L]]
  
  nclass <- (ncol(yval) - 2L)/2L
  yprob <- if (nclass < 5L)
    format(yval[, 1L + nclass + 1L:nclass],
           digits = digits, nsmall = digits)
  else formatg(yval[, 1L + nclass + 1L:nclass], digits = 2L)
  if (!is.matrix(yprob)) #this case only occurs for no split trees
    yprob <- matrix(yprob, nrow = 1L)
  ## FIXME: improve code
  temp <- paste0(temp, " (", yprob[, 1L])
  for (i in 2L:ncol(yprob)) temp <- paste(temp, yprob[, i], sep = " ")
  temp <- paste0(temp, ")")
  temp
},
```

**Comment by bethatkinson** [comment]
Thanks, I’ll take a look at this.  Beth

**Comment by eheinzen** [comment]
Thoughts on just taking `min(digits, 20)`?  Or perhaps just adding `nsmall=` as an argument to `print()`?

**Comment by bethatkinson** [comment]
I’d be fine with adding in the nsmall argument, but that it could be nsmall=digits, or something like that.
