### ISSUE TITLE
The logo png file has executable bit set

### ISSUE THREAD

**Issue by steve-s** [bethatkinson/rpart#8]
As reported by @lucaswerkmeister in oracle/fastr#119, the `rpart.png` file has `x` bit set (checked on the current CRAN release and the tip of the GitHub repo)

```
> ls -l ./man/figures/rpart.png
-rwxr-xr-x 1 steve steve 25414 Nov 25 20:36 ./man/figures/rpart.png
```

**Comment by bethatkinson** [comment]
thanks
